server:
  port: 7000
spring:
  application:
    name: atguigu-crowd-pay
  devtools:
    restart:
      enabled: true
  redis:
    host: 192.168.24.128
    port: 6379
  session:
    store-type: redis
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    instance-id: order6000
    prefer-ip-address: true
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
ali:
  pay:
    alipay-public-key: alipay-public-key
    app-id: app-id
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: merchant-private-key
    notify-url: http://xz2zsu.natappfree.cc/pay/notify
    return-url: http://xz2zsu.natappfree.cc/pay/return
    sign-type: RSA2
