server:
  port: 7000
spring:
  application:
    name: atguigu-crowd-pay
  devtools:
    restart:
      enabled: true
  redis:
    host: 192.168.24.128
    port: 6379
  session:
    store-type: redis
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    instance-id: order6000
    prefer-ip-address: true
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
ali:
  pay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnW7SyjQ/iCnSzP60ZrwLaITg8GjU3Mqie63VTbfp+NKcO6rsim4pYPIZYn2K14d4pjPFMFF7aXwg7v+/jPqFd8NbxdoP/v0H/KpeYV9x4NAALepYMUMB3K/8DLlJvFpZafW7V/ZyUIiDatNK8I49Lf7QFN7OYICnn9owRwrfdW26UHEYMtIYKiY5F+MgJOr8fIxCBM9DuSIKfwRm4xHNg5zy7752wzmLUKs/vP3ZsqdEDgYGgRik5atmy+dOArtDgq6HtqcDnQamT4YxR9x6DntyU/dbNxaHowIk4F6ZantR1BjkAbteK/tRlWFhiTLMHc5gXw5RZYM7JK76cdUPXQIDAQAB
    app-id: 2021000117604473
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCdbtLKND+IKdLM/rRmvAtohODwaNTcyqJ7rdVNt+n40pw7quyKbilg8hlifYrXh3imM8UwUXtpfCDu/7+M+oV3w1vF2g/+/Qf8ql5hX3Hg0AAt6lgxQwHcr/wMuUm8Wllp9btX9nJQiINq00rwjj0t/tAU3s5ggKef2jBHCt91bbpQcRgy0hgqJjkX4yAk6vx8jEIEz0O5Igp/BGbjEc2DnPLvvnbDOYtQqz+8/dmyp0QOBgaBGKTlq2bL504Cu0OCroe2pwOdBqZPhjFH3HoOe3JT91s3FoejAiTgXplqe1HUGOQBu14r+1GVYWGJMswdzmBfDlFlgzskrvpx1Q9dAgMBAAECggEAE9IPEcwQL5lsY8ixd7m3Cfqowzu/iOiuGjohf75m45/Ica6sRyVlakIwtfiuUUJKC0q7ScEIc5hgIRbry9kCkrhyxm8U0nqS1dmxNjspAC/PxfgaEGGqS1mQtx1gzijl1vRMGN/7Nm5pdTqS1cRiqXbKRcZjXzzzXam/qEITLhpm7EnSb5J0/1040bGHJw2f9BbuQfUy39DZuCiePNWqfM+k2sLhwd/qzIEH5swgmobnvkLlAackDz29K6p/94LmQeylCIiYxJ70iIKT28SOe2mN//r4QUaSd9DqXkUt5sgsqAUv2MMsEPpKK3kHzjG3NgHl25tYxNzdFxlqjdho1QKBgQDKW0k9wtpLXcxm5RNAeFcQF2CxcXDPZW9N897bueXzu2EU6mKUyYwAfw42F8fSj9TVARwsGDF53eUyoRBQ9jGD+uVWWNyFQn/UVP+VfpvRvHA3PERehmhgWpgTuiyiN90HnBqa4mxfXd74STEFqZhAkH584hT5Ld8ddz8Mi5TgwwKBgQDHKtbp4Fl0MSY34AW9lsXoLzf274jfdg2YvRbDPiXyF5h9604HXq3subpwMYMdy87LmPKQNVUSsZa4a8HuzrTR9zSLxa3opNARsVSs5u6dlhV84h4Fdoq6pZstIR7w5on0NQUFw+dfOyCAdeHiVeRIW2sCj6VIM36zCliTumlNXwKBgBlPQ6Di7zS//aHdAwRsSM9tbR2kh6yZDkvctcIbxUQv6puYGU5sywMA4UEoxkhyzvb5VZG6UO3iMBmeBZFqyZStW+Pp52MPhzeCjhkfpdOc0xhFhHOiMgnjKuREw/JiNFYQU0+OBGoFLq81UFlZ9f4VVIzAJkloUGC6GnuyNaPLAoGBAJkrQAazS/hIyCyWc7O/XUpX7gFRbAD2yDQbz4Ktq/8H2HWWXfbbAIUavOAFo+FpWQtI/9qZuWhb/R6teILQo00KgXWwvDM7dOz2ZLloDEBTKQlW2GG5La2nKLTHUQVRNu0BTXCGncymKzO/9Mzc42gmLiDVGfZx69GDdmV+KfefAoGAU4NHzowWKQpdcuveoGeUKoxTh6t1HWgi/E98xNYyEg5SMAtqLq6Zja4KymRGbYyVxNRcis6MJzr8J/KqzroLC5iopa2QEtRqFBFSUMOWLi1g+fXPBB2mQUj3Uk5SPNncJFSBWcYcHWkyKkhnFFHuebsw45GjIMqay86fKUAuF3I=
    notify-url: http://xz2zsu.natappfree.cc/pay/notify
    return-url: http://xz2zsu.natappfree.cc/pay/return
    sign-type: RSA2
