server:
  port: 2000
spring:
  application:
    name: atguigu-crowd-redis
  redis:
    host: 192.168.24.128
    port: 6379
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    prefer-ip-address: true
    instance-id: redis2000